#!/bin/bash

echo "🚀 Configurând deployment pe GitHub Pages..."

# Setează numele repository-ului
REPO_NAME="Kalina-AI"

echo "📋 Instrucțiuni pentru deployment:"
echo ""
echo "1. Mergi pe GitHub.com și creează un repository nou numit: $REPO_NAME"
echo "2. Selectează 'Public' pentru repository"
echo "3. NU adăuga README, .gitignore sau licence (avem deja)"
echo "4. După crearea repository-ului, copiază URL-ul (ar trebui să fie ceva de genul:"
echo "   https://github.com/USERNAME/Kalina-AI.git"
echo ""
echo "5. Rulează următoarele comenzi:"
echo ""
echo "# Adaugă remote origin (înlocuiește USERNAME cu username-ul tău GitHub)"
echo "git remote add origin https://github.com/USERNAME/Kalina-AI.git"
echo ""
echo "# Push codul pe GitHub"
echo "git push -u origin main"
echo ""
echo "6. Mergi la Settings > Pages în repository-ul tău GitHub"
echo "7. Selectează Source: 'GitHub Actions'"
echo "8. Workflow-ul va rula automat și va face deploy site-ul"
echo ""
echo "Site-ul va fi disponibil la: https://USERNAME.github.io/Kalina-AI/"
echo ""
echo "✅ Configurația este gata! Urmează pașii de mai sus pentru a finaliza deployment-ul."
