
import React from 'react';
import { X, Lightbulb, AlertTriangle, CheckCircle } from 'lucide-react';

interface AIInsightsPanelProps {
  isOpen: boolean;
  onClose: () => void;
  conversation: any;
}

const AIInsightsPanel = ({ isOpen, onClose, conversation }: AIInsightsPanelProps) => {
  if (!isOpen) return null;

  const mockInsights = {
    summary: [
      'Customer expressed frustration about delivery delays',
      'Agent successfully de-escalated the situation',
      'Resolution provided with tracking information'
    ],
    actionItems: [
      'Follow up within 24 hours with delivery update',
      'Send customer satisfaction survey',
      'Update internal process for similar issues'
    ],
    warnings: [
      'Customer mentioned competitor comparison',
      'Potential compliance issue detected in pricing discussion'
    ]
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-xl max-w-2xl w-full max-h-[80vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <h2 className="text-xl font-semibold text-gray-900">AI Insights</h2>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700 transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Summary */}
          <div>
            <div className="flex items-center space-x-2 mb-3">
              <Lightbulb className="text-blue-500" size={20} />
              <h3 className="font-semibold text-gray-900">Key Insights</h3>
            </div>
            <ul className="space-y-2">
              {mockInsights.summary.map((insight, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <div className="w-2 h-2 bg-blue-500 rounded-full mt-2 shrink-0" />
                  <span className="text-gray-700">{insight}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Action Items */}
          <div>
            <div className="flex items-center space-x-2 mb-3">
              <CheckCircle className="text-green-500" size={20} />
              <h3 className="font-semibold text-gray-900">Recommended Actions</h3>
            </div>
            <ul className="space-y-2">
              {mockInsights.actionItems.map((item, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <div className="w-2 h-2 bg-green-500 rounded-full mt-2 shrink-0" />
                  <span className="text-gray-700">{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Warnings */}
          <div>
            <div className="flex items-center space-x-2 mb-3">
              <AlertTriangle className="text-orange-500" size={20} />
              <h3 className="font-semibold text-gray-900">Attention Required</h3>
            </div>
            <ul className="space-y-2">
              {mockInsights.warnings.map((warning, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <div className="w-2 h-2 bg-orange-500 rounded-full mt-2 shrink-0" />
                  <span className="text-gray-700">{warning}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-gray-50 rounded-b-xl">
          <div className="flex justify-between items-center">
            <span className="text-sm text-gray-500">
              Insights generated by AI • Last updated 2 min ago
            </span>
            <button className="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors">
              Export Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIInsightsPanel;
